### ISSUE TITLE
Error EISDIR when loading documentation page.

### ISSUE THREAD

**Issue by w1wwwwww** [titaniumnetwork-dev/Oxide-Docs#3]
When I click on a link to a documentation page, I get an EISDIR error.

Steps to reproduce:
1. Go to [https://docs.titaniumnetwork.org/](https://docs.titaniumnetwork.org/)
2. Click on a link to a documentation page, such as [https://docs.titaniumnetwork.org/ultraviolet](https://docs.titaniumnetwork.org/ultraviolet)
3. See error.

Expected behaviour:
The proper documentation page loads.

![image](https://user-images.githubusercontent.com/26696846/203414634-31d1ac13-1028-46f6-b65e-848a3a822ce4.png)

**Comment by w1wwwwww** [comment]
Seems to be fixed now, I'm assuming it was an issue with my computer.

**Comment by QuiteAFancyEmerald** [comment]
No it was actually an issue node-static.
