### ISSUE TITLE
`yarn dev` and `yarn build` fails `createPagesStatefully`

### ISSUE THREAD

**Issue by luphoria** [titaniumnetwork-dev/Oxide-Docs#6]
[error.log](https://github.com/titaniumnetwork-dev/Oxide-Docs/files/10119904/error.log)
(Note: it went in an infinite loop, because I used command `yarn dev > error.log` to catch the error, but you can still see the syntax error)

```
  SyntaxError: /home/deck/Oxide-Docs/src/docs/services/nebula.mdx: JSX value sho
  uld be either an expression or a quoted JSX text. (7:11)
     5 |       {...props}
     6 |       components={components}>
  >  7 | <div align=center> 
       |            ^
     8 | <img src='https://nebulaproxy.nebula.bio/images/logo.png' width="100px"
   height="100px">
     9 | <h1>  Nebula </h1>
    10 | NebulaWeb is an official flagship of Nebula Services and Nebula Develop
  er Labs. NebulaWeb is a stunning, sleek, and functional web-proxy with support
   for thousands of popular sites. With NebulaWeb, the sky is the limit.
```

**Comment by mdoryammilwalrus** [comment]
I am just going to put this here but it just fails to build because of a error:
```
Error: error:0308010C:digital envelope routines::unsupported
```
(a DuckDuckGo search reveals that this is due to a security patch in NodeJS v17 and higher)

**Comment by luphoria** [comment]
Is this for you? because that isn't in my log at all

**Comment by mdoryammilwalrus** [comment]
Yes, it crashes while trying to build that page also. But I get that error also

**Comment by luphoria** [comment]
Now works.
